eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8081/eureka
server:
    servlet:
        context-path: /planningpoker/api/v1/arquivos
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        password: ${PGPASSWORD}
        url: jdbc:postgresql://localhost:5432/arquivos
        username: ${PGUSER}
    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: true
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
